name: Python Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run Task
        run: task hello
  
  python-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: "api/pyproject.toml"
      
      - name: Install the projects
        run: uv sync --all-extras --dev
      
      - name: Run lint
        run: task lint
      
      - name: Run tests
        run: task test
